# Configuración del Puente (MoveIt -> Controlador)
moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_controller

  arm_controller:
    # Namespace de la acción (estándar en ROS 2 control)
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - base_to_waist
      - waist_to_shoulder
      - shoulder_to_elbow
      - elbow_to_elbow
      - elbow_to_hand